# Generated by Django 5.1.4 on 2024-12-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=150)),
                ('giro', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
